lib/Bio/EnsEMBL/DataCheck/Checks/CurrentRegulatoryBuildHasEpigenomes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/RegulatoryFeatureIsActive.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Port of the following healthcheck: https://github.com/Ensembl/ensj-healthcheck/blob/release/94/src/org/ensembl/healthcheck/testcase/funcgen/RegulatoryFeatureIsActive.java
I used the final SQL instead of looping through the different objects. The hc mention that the SQL is slow but it only takes 3s for human. Ilias is having a look why he didn't used the final SQL in the hc, if he comes back to me, I will update the test.

New test/regulatory feature is active

---

lib/Bio/EnsEMBL/DataCheck/Checks/SequenceLevel.pm

Missing condition copied over from the old healthcheck.

ENSCORESW-2719: contig can be not null if only one assembly is stored

---

lib/Bio/EnsEMBL/DataCheck/Test/DataCheck.pm

This allows a more lax parsing for cases like AssemblySeqregion.

Allow some spaces and new lines while parsing sql

---

lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm

There's actually a lot of flexibility in how biotypes can be specified, so there's not loads to check. But the old BiotypeGroups healtcheck was really complicated, which masked the fact that it was doing unnecessary tests.
The BiotypeGroups healthcheck consistently failed (requiring annotation as "OK") when trying to deal with 'TEC' biotypes (TEC => To be Experimentally Confirmed), which have the group "undefined". The datacheck just doesn't bother trying to test anything about biotype groups that are undefined.
The HC also sometimes failed for non-vertebrate species, which had valid biotypes but weren't exactly like the HC was expecting; these were single-transcript genes where the biotype was not exactly the same between gene and transcript. That's been the norm in the past, but it's …

Datacheck for biotype groups

---

lib/Bio/EnsEMBL/DataCheck/BaseCheck.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
t/BaseCheck.t
t/DbCheck.t

The code was not properly handling the skipping of tests for collection databases. The skipping was done at the database level, with species_id=1 deciding whether tests were skipped for all species. Have now separated the logic of skipping a datacheck (which happens at the db-level, e.g. because tables haven't been updated) and the skipping of tests (which happens at the species-level). Seemed to make sense to rename the 'run_tests' method to 'run_datacheck', to match the structure/logic of the code.

Fix test skipping for collection dbs

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckFactory.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSubmission.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/EmailSummary.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/StoreResults.pm

New module that deals with datacheck submissions. This allows the pipeline to be used with an eternal beekeeper, isolating submissions from each other. Submission metadata is stored in a table in the hive, for easier lookup. The default is now to receive a single summary email per submission.
init_pipeline.pl can be used to create an empty database, and then each submission is a call to seed_pipeline.pl. The formatting of variables required by seed_pipeline.pl is a little unfriendly; a further task will be to create a simple script, analogous to scripts/run_datachecks.pl, to mask the complexity and enable people to more easily create/manage their own pipelines. Documentation needs to be updated accordingly.

Restructure datacheck pipeline

---

lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesNameUnique.pm
lib/Bio/EnsEMBL/DataCheck/Checks/StableIDUnique.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Adding datacheck for testing stable ID uniqueness across many databases/servers.
Tweaking datacheck for species name uniqueness, make it db-level rather than species-level for collection dbs.

Multi-database datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CoreTables.pm
lib/Bio/EnsEMBL/DataCheck/Checks/FeaturePosition.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Rewrote the logic of the tests, to minimise and simplify the queries hitting the db, based on the approaches used in the FeatureBounds and MetaCoord datachecks. Reduces run time by 2 orders of magnitude, down to <10 mins for human.

Make funcgen bounds check more efficient

---

.gitignore
config.json.example
lib/Bio/EnsEMBL/DataCheck/Checks/DataFilesExist.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
lib/Bio/EnsEMBL/DataCheck/Manager.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSubmission.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm
scripts/run_datachecks.pl
scripts/run_pipeline.pl
t/DbCheck.t
t/Manager.t
t/RunDataChecks.t

It's useful to be able to define a config file with all the parameters needed to run a set of datachecks; there are some rarely used parameters which are essentially constant, so it's a pain to have to specify on the command line.
These changes allow for a config file to be created once with the default parameters. Anything passed on the command line overwrites these defaults.

Add config file functionality

---

config.json.example
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
lib/Bio/EnsEMBL/DataCheck/Manager.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm
scripts/run_pipeline.pl
t/Manager.t
t/RunDataChecks.t

Extending config file to work with more parameters. This means that we'll be able to create a per-division config file which can be selected when running datachecks through a service, which will simplify that process for the user, and hopefully avoid things going in the wrong place.
Fix to make an explicitly provided registry work properly with collection dbs.
Tidy up output_file specification; append job id to the filename to prevent unintended overwriting and make it easier to find relevant result sets.

Datacheck config and registry improvements

---

lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysMultiDB.pm

The funcgen 'mirna_target_feature' table has been modified for release 97 (see https://github.com/Ensembl/ensembl-funcgen/blob/master/sql/patch_96_97_e.sql).
Up until now, mirna_target_features were linked to genes via the 'object_xref' table. From now on, they will be linked via the new 'gene_stable_id' column.
This PR updates the relevant foreign key checks.

funcgen updates

---

lib/Bio/EnsEMBL/DataCheck/Checks/DensityFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DensitySNPs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneCounts.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneGC.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GenomeStatistics.pm
lib/Bio/EnsEMBL/DataCheck/Checks/PepstatsAttributes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SNPCounts.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Three new datachecks, for SNP counts and density calculations for features and SNPs. Categorised datachecks into core and variation specific groups, as well as a more general 'statistics' one.

Statistics pipeline-related datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayableSampleGene.pm
lib/Bio/EnsEMBL/DataCheck/index.json

added critical datacheck DisplayableSampleGene to avoid issues such as https://github.com/Ensembl/staging-patches/pull/251
Created with:
$ perl -I lib scripts/create_datacheck.pl -n DisplayableSampleGene -d 'Sample gene is displayable and has web_data attached to its analysis' -g core_handover -db core -t meta,gene,analysis,analysis_description

added critical datacheck DisplayableSampleGene

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareVariationEvidence.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion of HC ComparePreviousVersionValidationStatus. ENSVAR-1970
Uses a join on attrib and attrib_tables

Datacheck for comparing variation counts by evidence

---

lib/Bio/EnsEMBL/DataCheck/Checks/EmptyVariationTables.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion of HealthCheck EmptyVariationTables.java - ENSVAR-1630
In future the meta table will be used to determine which tables should/should not have data. This information is not currently in meta.
On failure it would be useful if the is_rows_nonzero (and cmp_rows) could have a diag_message

Datacheck for empty variation tables

---

lib/Bio/EnsEMBL/DataCheck/Checks/InterProFeatures.pm

So that we actually check the display_label field, and not the result of a equality comparison...

Fixing typo in SQL condition

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledAnalysis.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesTaxonomy.pm

The assumption that the taxonomy ID will always be found is invalid, so make that an explicit test, and then proceed conditionally.
(This error was caused by the same 4 fungi species that messed up compara, so at least we now have a way to check for that in the future...)

Datacheck module was dying with an error, if taxonomy node was not defined

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneStableIdDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/StableIdDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Merged GeneStableIdDisplayXref and TranscriptStableIdDisplayXref Hcs into this DC.This check that gene/transcript display_xref are not set to the stable_id. The DC is collection friendly.

Stable id display xref

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGeneNames.pm
lib/Bio/EnsEMBL/DataCheck/index.json

…as doing a lot of checks including overall number of projected gene names, lost of sources, change from one source to another, no change in source. We believe with James that it makes more sense to just look at the overall number of projected Gene Names and report big drops. The DC is compatible with collections

Ported ComparePreviousVersionProjectedGeneNames HC. The original hc w

---

lib/Bio/EnsEMBL/DataCheck/Checks/ProteinFeatureLength.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ProteinFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ValidTranslations.pm
lib/Bio/EnsEMBL/DataCheck/index.json

New checks for:
- proteins labelled as non-translating that nonetheless have a translation.
- protein feature accession formats (replicates and extends functionality of HC generic.Accession)
- protein features are not longer than the associated translation (replicates functionality of ProteinFeatureTranslation and EgProteinFeatureTranslation)

New translation/protein feature checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareSchema.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm

Make CompareSchema a bit more robust wrt trailing whitespace, and flip the is_deeply parameters so that the failure messages make more sense.

Update CompareSchema datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/MultipleSeqRegions.pm
lib/Bio/EnsEMBL/DataCheck/Checks/PhenotypeMultipleSeqRegions.pm
lib/Bio/EnsEMBL/DataCheck/index.json

The check that phenotype_feature does not have a single seq region was failing for some metazoa databases. The has been made a separate check and only for vertebrate database

Update to multiple region update

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/Example_conf.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm

Cannot pass DBA object from one hive module to another, but the database parameters are still useful for diagnostics, so pass them as a hash instead.

Fix for embedded datacheck output

---

lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyLevel.pm
lib/Bio/EnsEMBL/DataCheck/index.json

The existing `ForeignKeys` datacheck has been adapted to the compara use case, i.e. using the foreign keys definitions in the `table.sql` file, rather than the `foreign_keys.sql` file that other teams use.
This datacheck includes the functionality from all `compara.ForeignKey*` healthchecks. It seems to run in reasonable time, so I don't see a pressing need to split it out in order to run in parallel. (It's a bit tricky to do anyway, now that most tests are derived from the SQL file - you'd probably have to do some rather inelegant regex matching on tables names).
There are several `species_tree_node` and `genomic_align_tree` checks (Lines 89-96) which were defined in the HCs but which are not present in the `table.sql` file. The comparable `gene_tree_node` checks _are_ in the SQL file, …

Foreign Key datacheck for compara

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignTreeTable.pm

Fix following comments on PR #188
The test with `row_totals` was not appropriate and the check was the wrong way around, now using `cmp_ok` with the "expected" and "got" counts.

Change of logic to better fit test

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyLevel.pm

This meta key is used by Compara and it doesn't have an `species_id` associated.

Bugfix: add 'division' as a special meta key

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckMethodLinkSpeciesSetNames.pm

Species sets that were created long time ago (before release/80) are likely to not match the current naming protocol, so they will make this test fail. Added a threshold control to skip them.

Skip species sets from before release 80

---

lib/Bio/EnsEMBL/DataCheck/Checks/AssemblySeqregion.pm

An assembly can't be longer than its components (unless there are special cases that I am unaware of).

Also check when the assembly length is too long

---

lib/Bio/EnsEMBL/DataCheck/BaseCheck.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckComparaStableIDs.pm
scripts/run_datachecks.pl

Detect successful subsequent attempts at running tests within the harness (e.g. if the harness fails initially due to I/O problems).
(Couple of other minor fixes included, to avoid multiple trivial PRs...)

Fix for detection of datacheck failures

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckJSONObjects.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSyntenySanity.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckTableSizes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareMSANames.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

Hello
These are four unrelated changes:
1. Minor comment fix
2. Test the objects as they come instead of preloading them into memory (don't need to allocate GBs of RAM any more to run the DCs)
3. Fix a Registry bug whereby database connections are closed at the handle level without letting the object now. Causes "MySQL server has gone away" errors
4. Got rid of some Compara-specific code

Misc. fixes

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyCardinality.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm
lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Adding new tests to some existing core-db-related datachecks:
* Check for non-NULL gene versions for vertebrates
* Conditionally check for presence of 'strain.type' meta_key
* For GENCODE species, check that meta data has been updated if the geneset was updated, and that web_data for tracks has the correct GENCODE version
These address JIRA tickets ENSPROD-4862, ENSPROD-4339, ENSPROD-5000.

Updated datachecks

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSubmission.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
scripts/parse_results.pl
scripts/run_pipeline.pl
t/DbCheck.t

- Enable datacheck pipeline to accept a db name as input. This is particularly useful for running across a single collection db (or a subset of them).
- Slightly friendlier error message when a registry is missing. Include db name in the TAP output; it's used as the filename, but that's not much help if you're viewing results through a GUI, or want to merge output files together in order to consolidate results for easier inspection.
- New script to parse TAP output into JSON, and merge output from multiple files.

Improvements to datacheck pipeline, and output parsing

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignGenomeDBs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignMTs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignTreeTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckMSANames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckMultipleAlignCoverage.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareMSANames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MultipleGenomicAlignBlockIds.pm

Jira ticket: [ENSINT-334](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-334)
_EPO\_LOW\_COVERAGE_, a `method_link.type` has been renamed for e101 to _EPO\_EXTENDED_ to better reflect what actually it is.
We use the `method_link.type` in the datachecks to access the compara API `method_link_species_set`.

Rename EPO_LOW_COVERAGE->EPO_EXTENDED in compara datacheck modules

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckConservationScorePerBlock.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGOCScoreStats.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignMTs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckMethodLinkSpeciesSetNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckWGACoverageStats.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm

This PR was intended to replace the `class` filters with `type` in several places in order to be more consistent across the HCs, but I also found two occurrences of `compara_prev` that needed to be replaced (they were introduced in parallel of my PR #206 , that's why I had missed them).
I've left some occurrences of `class` in ForeignKeysCompara because it's meant to be really generic, but all others DCs are now using `type` only.
(leaving this as a draft because I want to check something with Cristi first)

Misc Compara changes

---

lib/Bio/EnsEMBL/DataCheck/Checks/AssemblySeqregion.pm

There is at least one assembly (_Ciona intestinalis_) which violates the stricter condition that was added - this doesn't exactly make sense, it means that there is a "gap" at the end of the sequence. It would be customary to trim those trailing Ns; but the datacheck needs to tolerate existing assemblies where this is not done (since it does not cause any errors, _per se_).
If this stricter condition is useful as a warning, it could be added as an advisory datacheck.

Revert "Also check when the assembly length is too long"

---

lib/Bio/EnsEMBL/DataCheck/BaseCheck.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
scripts/parse_results.pl
t/DbCheck_noncore.t

Catch run-time errors and present them as test failures, so that a) pipelines can run to completion, and b) users get useful information on errors.
Minor fix to parsing script also included.

 Catch run-time errors and present them as test failures

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSubmission.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSummary.pm

Make the timestamp in the 'output' result parameter reflect the completion of all jobs connected to the submission job. Also add a 'runtime_sec' parameter, for convenience.

Fix datacheck pipeline end timestamp

---

lib/Bio/EnsEMBL/DataCheck/Checks/XrefPrefixes.pm

The datacheck failures that you saw were valid - there is a genuine problem with these xrefs, for which there is a known bug: https://www.ebi.ac.uk/panda/jira/browse/ENSINT-438.
I have a fix lined up, as per https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-5382.

Revert "When running the XrefPrefixes on vertebrates post xrefs, we discovere…"

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankSets.pm
lib/Bio/EnsEMBL/DataCheck/index.json

General test for set column types. For ENSVAR-3161  to check that variation_feature.consequence_types is not empy string

Check for empty strings in set columns

---

lib/Bio/EnsEMBL/DataCheck/Checks/StructuralVariationFeature.pm
lib/Bio/EnsEMBL/DataCheck/Checks/StructuralVariationSomatic.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Structural variants imported from COSMIC must have somatic = 1 in two tables: structural_variation and structural_variation_feature

Add variation test - check somatic structural variants

---

lib/Bio/EnsEMBL/DataCheck/Checks/PhenotypeMultipleSeqRegions.pm

Fix to handle species in e101 with single phenotype_feature record

Skip test when 0 or 1 phenotype_feature records

---

lib/Bio/EnsEMBL/DataCheck/Checks/Denormalized.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MultipleSeqRegions.pm
lib/Bio/EnsEMBL/DataCheck/index.json

The Denormalized datacheck needs a set of tables to be defined, in order to prevent this long-running check from executing redundantly.
For MultipleSeqRegions, base the skipping condition on our expectation that if multiple seq_regions are present in the variation db, there will be variants annotated on more than one seq_region - this avoids the need to make division-based assumptions (based on discussion in #241).

Updating Denormalized and MultipleSeqRegions

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareOntologyTerm.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
scripts/run_datachecks.pl

Determine old dbnames for ontology and compara dbs, by regexing the release versions. This method wouldn't work for the names of other db types, due to the 'assembly version' suffix, but it's fine for the simpler name patterns (which are not easily accessible in the metadata db).
Removed the skip block from the CompareOntologyTerm datacheck - it wouldn't work any more, because DbCheck wil now always cause a failure in the absence of an old ontology db. Such a db should always be available on a server (in contrast to a core db, which might be brand new); if the old ontology db cannot be found, then some run-time parameters must have been incorrect.

Determine old version of compara and ontology databases

---

lib/Bio/EnsEMBL/DataCheck/Checks/GOXrefEvidence.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefTypes.pm

New test for GO xrefs to only be present on transcripts.
Making SQL for GO Evidence datacheck species-specific.

Update datachecks related to GO xrefs

---

lib/Bio/EnsEMBL/DataCheck/Checks/DNAFragCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneTreeHighlighting.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GenomeDBCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagGERP.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagMaxAlign.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagMultipleAlignment.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagPairwiseAlignment.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagSynteny.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagThresholdDs.pm
lib/Bio/EnsEMBL/DataCheck/Test/Compara.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Adding new compara datachecks.
ForeignKeys gets an update, because there was a healthcheck specific to the ancestral db for the dna table, which is generally useful.
Added to ForeignKeysCompara, to check for MLSS tag links.
Batch of MLSS tag datachecks converted from healthchecks, and a new module, Bio::EnsEMBL::DataCheck::Test::Compara, which contains test methods used by multiple datachecks, to prevent repetitive code.
Gene tree highlighting datacheck, which is for non-verts only, and is not part of the 'compara' group, because it only makes sense to apply it after handover, when the Production team have run the relevant pipeline.

New compara datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGeneGainLossData.pm

As it stands, CAFE is decided on a per-division basis only. 
This PR updates the DC to also check the method_link_species_set_tag table to decide whether gain/loss data exists on a per-mlss basis.

Detect CAFE using an mlss_tag

---

lib/Bio/EnsEMBL/DataCheck/Checks/NCBIGeneLabels.pm
lib/Bio/EnsEMBL/DataCheck/index.json

If a RefSeq geneset has been loaded with arbitrary generic IDs as stable_ids, the display_xref must be set in order for the browser to show the appropriate accession.
This datacheck will prevent recurrence of known bug ENSINT-440.

 New datacheck to ensure correct display of NCBI gene and transcript accessions

---

scripts/run_datachecks.pl

Not really a bug, but in case we want to check the ancestral database against a compara database, `ancestral_sequences` is the best way of linking both (we have such a check as a separate script that we might consider porting to the DC framework).
`Ancestral sequences` is indeed the default Registry name for Vertebrates, but it only works because `ancestral_sequences` is added as an alias.

"ancestral_sequences" is what the Compara API uses to link GenomeDBs to Core DBAdaptors

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledAnalysisVersion.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MTCodonTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyBRC4.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionBRC4.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesTaxonomy.pm

3 BRC4 check update, as well as other corrections:
- ControlledAnalysisDescription should be skippable if there are no analysis in the database, like it is done for ControlledAnalysis
- Fix Species taxonomy when removing the strain from the scientific name, + also remove "strain" in addition to "str."
- Fix MTCodonTable to allow cases when there are several mitochondria (see Phlebotomus papatasi with 18).

Brc4 fixes

---

lib/Bio/EnsEMBL/DataCheck/Checks/PhenotypeDescription.pm

Updating known and accepted phenotype descriptions in check.
Before this change the DC would fail if 'none' would be present as a phenotype description. This is accepted as long as the phenotype class attrib is 'non_specified'.

remove known phenotype descriptions

---

lib/Bio/EnsEMBL/DataCheck/Checks/ProteinTranslation.pm

ProteinTranslation can take a very long time on long sequences.
Sorting the transcripts by seq_region and start ensures the dna sequence
cache is used more effectively.
Example of speedup: from 1.5h to 30min on Aedes aegypti

Sort transcripts to use the dna cache

---

lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionSynonyms.pm
lib/Bio/EnsEMBL/DataCheck/index.json

(in the same coord system, for a given species)
If a seq_region synonym happens to be the name of a different
seq_region, then the API will prioritize the synonym over the name of
the seq_region, and so will be using the wrong sequence.
This happened in Phlebotomus papatasi, where the name of the scaffolds
were from a version of the assembly prior to its submission to INSDC
(the sequences ended up identical, but with different names in the final
version, hence the clash).

Check that seq_region synonyms are not names of other seq_regions

---

lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionTopLevel.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SequenceLevel.pm

Two datachecks were incorrectly reporting failures, because they did not account for edge cases.
- SequenceLevel: To account for assembly mappings that involve old contig-only assemblies, the SQL in one test was updated to count distinct versions, not seq_region names.
- SeqRegionTopLevel: Handle partial population of the assembly table, where some seq_regions of a particular coord_system are components, and others are unassembled top-level regions.

Fixes for two seq_region-related datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareMetaKeys.pm
lib/Bio/EnsEMBL/DataCheck/index.json

New datacheck to detect assembly and/or geneset changes that are not accompanied by an updated meta_key.

Detect assembly/geneset change

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

Fix problem arising from the registry assuming that species_id=1 if it is not explicitly specified. This was being supplied in one part of this module (used by most datachecks), but not in another, when the registry is reloaded by a datacheck (as, for example, in a 'Compare*' datacheck that connect to the metadata database).
Further details in JIRA ticket ENSPROD-5471.

Fix for 'Compare*' datachecks in databases without species_id=1

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareGOXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGOXrefs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGeneNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedSynonyms.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DisplayXrefExists.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HGNCMultipleGenes.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Also, disable DisplayXrefExists for non-vertebrates. Reduce threshold for reporting differences with previous version, from 80% to 66% - too noisy otherwise, which makes it hard to spot significant problems.

Create new datacheck groups for xref-related pipelines.

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm

When running this datacheck against a core-like database with the 'run_datachecks.pl' script, we need to force the core database to be loaded into the registry (it's lazy-loaded, but for reasons that aren't clear, loading isn't triggered as expected by the calls to the gene adaptor). This is not an issue when running within a pipeline, because the registry will automatically have been loaded in that case.

Force load of core db in GeneBiotypes, when run for core-like dbs

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesTrees.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Utils.pm
lib/Bio/EnsEMBL/DataCheck/index.json
t/Utils.t

We only detected in `e101` that the species tree in vertebrates had not been merged when the `ForeignKeysCompara` datacheck was run prior to handover. Here we have a species tree specific DC that checks that all expected species trees with linked mlsss are present in the release database. The FK check for the species tree has been moved here too, so that it is not duplicated.
There is some overlap in the tests within `CheckSpeciesTree`, happy to discuss. Was aiming to provide more specific descriptions in the non-fk derived tests to make failures easier to understand.
- [Add a datacheck to check that all species-tree are present in the database](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-3602)
`ForeignKeysCompara` was not quite compatible with embedding in our pipelines because …

Move test out of ForeignKeysCompara to new DC

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm

I don't like when people use SELECT inside SELECT statement when it can be done with JOINs but the query with JOINs is taking forever on a server with ~2000 databases whereas the new query is taking 0.02s

Speed up SQL query on INFORMATION_SCHEMA.COLUMNS and INFORMATION_SCHEMA.TABLES

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckConstrainedElementTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignments.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSynteny.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/index.json

`ForeignKeysCompara` had duplicate fk() tests. Some of these have been removed altogether, since the duplicate tests were repeats of the natural fk() checks with schema changes in compara's `table.sql`.
[Remove redundant checks from the ForeignKeysCompara DC](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-3740)
Some of the above duplicate tests that were removed were included with constraints on the wrong table, and an `explain()` on each query showed them to be impossible. As some of these were duplicates and removed nothing further was needed to alter them. However some were presumably looking for missing data and not intended as fk() checks at all, in this instance additional tests have been included.
[Fix impossible queries in the ForeignKeysCompara …

Remove duplicate fk tests and fix constraint issues

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareSynonym.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DisplayXrefFormat.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateTranscriptNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GOXrefEvidence.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneDescriptions.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HGNCNumeric.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HGNCTypes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/LRG.pm
lib/Bio/EnsEMBL/DataCheck/Checks/StableIdDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UnreviewedXrefs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefFormat.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefPrefixes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefTypes.pm
lib/Bio/EnsEMBL/DataCheck/index.json
scripts/update_group.pl

New script to make it easier to add and remove groups from datachecks. Supply a group name to add or remove, and a list of datachecks, and the relevant files will be updated.
And xref groups updated, for more control when executing in a pipeline.

Update group script

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignments.pm

`POLYPLOID` comprehends the polyploid self-alignments we compute in Compara. I have noticed it was missing when this DC has failed for plants handover.

Missing alignment method

---

lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysMultiDB.pm

The naive comparison was intractable, due to the very large number of motif_features for human. This update uses batches, attempting to retrieve the motif_feature_variation stable IDs from the fungen db (via the API). For human, with ~5 million IDs, this takes ~5 minutes.
Regulation team also advised that motif_features are not dependent on having a regulatory build, so removed the skip block (could have moved it further down the module, but the benefit of that would be minimal, since we've already connected to the funcgen db for the motif_feature test, so compete removal simplifies the code.)

Reinstate motif_feature_variation check

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm

Otherwise we create complications for collection databases. Also, loop over genes slightly differently, to reduce memory usage.

Only load DNA db if we have a non-core db in GeneBiotypes

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/index.json

In PR #283 the ForeignKeysCompara DC was sorted through to remove redundant, duplicate tests and tests with constraints. The tests that were not duplicate or redundant were to be replaced by other DCs. An oversight skipped the replacement of Homology-MLSS checks. This PR replaces that check.

Missing homology MLSS check from PR #283

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignments.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesVariation.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DNAFragCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GenomeDBCore.pm
lib/Bio/EnsEMBL/DataCheck/Utils.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Copy of #285 that resolves merge conflicts.

Cross-database compara datachecks + conflict resolution

---

lib/Bio/EnsEMBL/DataCheck/Checks/ExonRank.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Some of the file dumps failed, because exon ranks were not sequential - it seems like some API methods for constructing exon lists for a transcript use 'rank - 1' as an array index. So you end up with an 'undef' in the exon list, which makes things fall over. This update checks that ranks are sequential; a pre-exiting test checks that every transcript has a rank 1 exon. Together, these ensure that exon ranks meet the API's assumptions.

Test for sequential exon rank

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareMetaKeys.pm

Hi @james-monkeyshines , 
while running 103 critical core datachecks I encountered
not ok 4 - Gene IDs, positions, and biotype groups are the same between theobroma_cacao_criollo_core_50_103_1 and theobroma_cacao_criollo_core_49_102_1
ensembl-datacheck/lib/Bio/EnsEMBL/DataCheck/Checks/CompareMetaKeys.pm line 141.
Since these are identical cores (the 1st in pl1, the 2nd in st3) apart from strain metakeys, I went back an ran the SQL query directly. It seems the order of results is not guaranteed, so I added an ORDER BY statement at the end and it seemed to work on my example. Now both databases return the same geneset details. Hope this helps.

sort results of geneset_details JOIN query 

---

lib/Bio/EnsEMBL/DataCheck/Checks/ExonBounds.pm

The ExonBounds datacheck was using vast amounts of memory when dealing with pig otherfeatures, which has 40 million exons... Use an iterator, rather loading everything into memory.

Reduce memory usage in ExonBounds datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareMetaKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CoreTables.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DNAFragCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysMultiDB.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GenomeDBCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaCoord.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Manager.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/index.json

The datachecks occasionally fail due to I/O issues related to the config and history json files. Increase robustness by trying to trap errors and report more useful messages.
Support new pipeline that runs the datachecks that check for synchronisation between core and non-core dbs (small change to pipeline, new 'core_sync' group) cf https://github.com/Ensembl/ensembl-production/pull/476.

Handful of fixes and new "core_sync" group

---

lib/Bio/EnsEMBL/DataCheck/Checks/DatabaseSpeciesName.pm
lib/Bio/EnsEMBL/DataCheck/Checks/RepeatFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm
lib/Bio/EnsEMBL/DataCheck/index.json

- VersionedGenes: Handle databases with multiple 'genebuild.methods'
- RepeatFeatures: Repeat features are not mandatory for virus databases.
- DatabaseSpeciesName: It has become apparent that it is necessary for the database name to match the 'species.production_name' meta_key - change the datacheck for this from advisory to critical.

Sundry fixes

---

lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagHomology.pm

Homology MLSS tags are not only related to protein trees: we have ncRNA tree tags as well. So check if these should be there or not based on the gene trees available in the database.

Check tags based on the gene trees available

---

lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionSynonyms.pm

Having a synonym that matches a name is legitimate if the coord_systems are different; it is used to redirect users from scaffolds to chromosomes for patches in human and mouse.

Force SeqRegionSynonyms to look within a coord_system.

---

lib/Bio/EnsEMBL/DataCheck/Checks/WhitespaceAdvisory.pm
lib/Bio/EnsEMBL/DataCheck/Checks/WhitespaceCritical.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Carriage returns in fields are problematic for dump files; easiest thing to do is remove them from the databases, and enforce continued absence with a datacheck. It's also useful to know about newlines or tabs in fields, but these do not present a particular problem for dumps, so checking those is done in a separate advisory datacheck.

Check for carriage returns in database varchar/text fields

---

lib/Bio/EnsEMBL/DataCheck/Checks/AssemblySeqregion.pm

Need to check whether a component seq_region in the assembly table has an end value greater than the seq_region.length. (Formerly only did this for the assembled seq_regions.)

Update AssemblySeqregion to check 'assembly.cmp_end'

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCompara.pm

In case the `multi` "formula" is not found, use our standard alias as the species name for the taxonomy database.

Add compatibility with Compara's registry config file

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankSets.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyAssembly.pm
lib/Bio/EnsEMBL/DataCheck/index.json

For all VARCHAR and ENUM type fields, we prevent empty strings, as long as the fields are NULLable. For variation dbs, SET type fields are also checked - but it makes sense to extend this to dbs with the core schema. There are only two such fields, `coord_system.attrib` and `biotype.db_type`. In the current set of core and core-like dbs, the latter never has an empty string, and it occurs in the former for only a few vertebrates. But those few vertebrates are important, because those rows deal with mappings between assemblies, and our datacheck for verifying those assumes NULL values. We could make the assembly mapping datacheck more complicated to handle empty strings, but we've already got a complicated set of conditions to deal with all the different permutations. And it seems sensible …

Prevent empty strings in 'SET' fields

---

lib/Bio/EnsEMBL/DataCheck/Checks/UniqueKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/index.json

See https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3564 : UNIQUE KEYs that comprise a column that is NULL-able allow duplicated rows if they contain one NULL.
This is not something we want in the Compara schema, and it's caused some issues with the `theobroma_cacao` renaming this release, so here is a new DC to check those. It's structured the same way as ForeignKeysCompara and is quite generic. It could probably be applied onto other database types, should people need to.

Added a check to test the UNIQUE KEYs

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledAnalysis.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ControlledAnalysisVersion.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ControlledMetaKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysControlledTablesCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysControlledTablesVariation.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm
lib/Bio/EnsEMBL/DataCheck/Manager.pm
lib/Bio/EnsEMBL/DataCheck/Utils.pm
lib/Bio/EnsEMBL/DataCheck/index.json
t/Utils.t

Running the complete foreign key check in the Production DB Sync pipeline was taking way too long, and was largely redundant, so introduce new datachecks which only test the foreign keys that are affected by the sync. This involved a little bit of refactoring of the code for parsing the relationships from a file, in order to prevent code duplication. Also tweaked group membership a little, so that the pipeline can refer to the 'controlled_tables' group.

Production DB-specific foreign key datachecks

---

lib/Bio/EnsEMBL/DataCheck/Manager.pm

In the event of a locking error when opening a config file, try again after a 2 second delay.

Catch 'flock' errors when opening config file

---

lib/Bio/EnsEMBL/DataCheck/Checks/PlastidsAnnotated.pm

The slice adaptor's fetch_by_region method returns unwanted partial matches, which causes the datacheck to spuriously fail for chimp. Workaround this by double-checking plastid seq_region names.

Adding workaround to PlastidsAnnotated datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm

Repeatmodeler is not currently used to mask the genome for subsequent analyses and should not be used to mask the genome for the ftp dumps (discussed in email) - therefore, the key for "repeatmask_repeatmodeler" is not needed in the meta table - skip it in the DC check.

Exclude the repeatmask_repeatmodeler logic_name from the DC 

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm

It is not an incrementing number, it's intended to store the name for an imported geneset, as used by the external annotator.
Made it a little more complex than strictly necessary, in order to more easily accommodate additional future patterns that we do not want to match (mirroring the existing functionality, which is based on matches rather than mismatches).

Catch incorrect usage of 'genebuild.version' meta_key.

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm

Tests of url meta_keys need to tolerate special case of 'www.ensembl.org' and empty strings.

Update MetaKeyFormat url tests

---

lib/Bio/EnsEMBL/DataCheck/Checks/XrefTypes.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Making the XrefTypes datacheck critical, and a member of the 'core' group - databases that fail this datacheck can break biomart building, and cause web display problems.

Making the XrefTypes datacheck critical

---

lib/Bio/EnsEMBL/DataCheck/Checks/Karyotype.pm
lib/Bio/EnsEMBL/DataCheck/index.json

To detect missing cytogenic bands when assemblies are updated.

Make Karyotype datacheck critical

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/ConvertTapToJson.pm

There should always be output from a datacheck run - but, if something has gone wrong, output might not be written. This would get picked up and reported when the run completes - but the jobs for converting to json were failing before then, and the datacheck process was left hanging. So, make that step robust to the absence of output.

Making conversion of output to json more robust

---

lib/Bio/EnsEMBL/DataCheck/Checks/ExonBounds.pm

Datacheck was relying on the assumption of linear regions, in order to make the queries a bit simpler. But it was failing to handle origin-spanning genes in bacterial circular regions; so need to be a bit more long-winded, to account for those. Introduce four separate queries, one for transcript start and one for transcript end, for each strand.

ExonBounds fix for circular chromosomes

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyAssembly.pm

This patch makes core critical check MetaKeyAssembly case-sensitive @james-monkeyshines 
This was tested on pl1 with musa_acuminata_core_51_104_2 while fixing https://github.com/Ensembl/staging-patches/pull/443

add MD5 so that string comparison is case sensitive

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledAnalysisVersion.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Check on analysis db_version is likely to fail for spurious reasons - too noisy, so remove from all groups for now. It is likely that this datacheck would only be useful for a subset of analyses, because there is little to be gained by updating databases to ensure consistency across the board.

Remove analysis db_version check from all groups

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareProteinFunctionPredictions.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Compare counts in protein_function_predictions and protein_function_predictions_attrib with counts from the previous release. Both tables get updated every release for human. The new dc will help spotting any missing data like we had for release 102 https://www.ebi.ac.uk/panda/jira/browse/ENSINT-647.

New dc cmp protein feature

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareVariationFeatures.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

Include additional condition to catch cases where old versions of both core and variation dbs are needed within a datacheck. And add the database names to the test descriptions, to make debugging easier.

Make old_dba retrieval more robust

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm

Added repeat detector to the list of logic names to be skipped under repeat.analysis meta keys.

hot_fix/repeatdetector_metakey

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareGOXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGOXrefs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareSynonym.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareXref.pm
lib/Bio/EnsEMBL/DataCheck/Test/DataCheck.pm
t/TestDataCheck.t

Passing `minimum_count` to `row_totals` or `row_subtotals` sets the minimum number of rows that have to be returned by the SQL statemets for the test to be performed.
The test passes automatically if **both** counts returned by the compared databases are below `minimum_count`.

Add optional miminum_count parameter to row_totals & row_subtotals

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankEnums.pm
lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckComparaStableIDs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckDuplicatedTaxaNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckReleaseConsistency.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckReleaseNulls.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSequenceTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesSetTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CigarCheck.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SchemaPatchesApplied.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SchemaType.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SchemaVersion.pm
lib/Bio/EnsEMBL/DataCheck/index.json

- Most changes simply involve adding new group to existing checks.
- Some minor exceptions included into `ForeignKeysCompara` for both `compara_references` and `compara_homology_annotation`.
- Minor alteration in `CheckHomologyMLSS` to search for specific `ENSEMBL_HOMOLOGUES` `method.type` for `compara_homology_annotation`.

New Compara Groups for RR

---

lib/Bio/EnsEMBL/DataCheck/Checks/SchemaVersion.pm
lib/Bio/EnsEMBL/DataCheck/Utils.pm
lib/Bio/EnsEMBL/DataCheck/index.json

`SchemaVersion` was working in our previous `compara_references` pipeline because we were using release numbers in the same fashion as the release databases, but we have decided to create a master-like database instead (names `ensembl_compara_references`), so the release number as been removed and this DC is no longer applicable.
For the homology annotation pipeline, we have modified our schema to make things easier for us internally: since we use `InnoDB`, we are taking advantage of the `ON UPDATE CASCADE` option to automatically update some keys, so `ALTER TABLE` is now part of our schema. Thus, `Utils::foreign_keys()` method has been updated.
Both edits have been tested in the [latest run of our `UpdateReferencesDB` pipeline](http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&usern …

Remove SchemaVersion from compara_references and update Compara schema

---

lib/Bio/EnsEMBL/DataCheck/Checks/PlastidsAnnotated.pm

Method returns objects rather than synonym strings - need to call the name method on the synonym objects.

Fix for PlastidsAnnotated datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/AttribValuesExist.pm
lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptSupport.pm
lib/Bio/EnsEMBL/DataCheck/index.json

CCDS xrefs are required for APPRIS annotations, so they need to be in the human and mouse databases at the point of handover (because the data is immediately dumped after handover and passed on to the APPRIS team).

Add check for presence of CCDS for human and mouse

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm

As per discussions with James and Guy, I've updated the repeat masking conditional metakey checks so that red isn't skipped for the plants division.

Adding some division specificity to repeatmasking metakey checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm

Additional changes for rapid release in Compara, in particular the per-species compara databases. 
- The homology MLSS may not be retrievable using the traditional compara API, so a more simple check is reverted to. This should be fine because the same data is already tested in the pipeline, where the API does work.
- The reference genomes are not retained in the per-species compara database, so a reduced `ForeignKeysCompara` check is necessary, although again, the data is checked in the pipeline first, so this should be enough.
[ENSCOMPARASW-3545](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-3545)
Tested in homology annotation pipeline database, main release database and per-species compara database

Changes to account for per-species compara databases

---

lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysMultiDB.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSubmission.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
scripts/run_datachecks.pl
scripts/run_pipeline.pl
t/DbCheck.t
t/DbCheck_noncore.t
t/DbCheck_old.t
t/Manager.t
t/RunDataChecks.t

Make server_uri and old_server_uri multi-valued.
For old_server_uri, we simply loop through the list, looking for the old version of the relevant db, stopping when we find it.
For server_uri, it remains as an alternative to specifying a registry_file, and in this case we loop through all values, adding them to the registry. There is some additional functionality, however - if both registry_file and server_uri are given, then only the registry is loaded by default. But, if an ancillary database (e.g. a core db needed for a corelike datacheck) is required, we first loop through the server_uri values, stopping when we find it; if not found there, we look in the registry. This functionality allows us to have a generic all-purpose registry file, which we can override for specific use cases, …

Better configuration of available servers/databases

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignTreeTable.pm

Sometimes some leaves in `genomic_align_tree` were ancestral sequences.
The new code checks if all internal nodes are ancestral sequences and all leaves from extant species.
**Related JIRA tickets:**
- ENSCOMPARASW-4084
- `$sql_4` fetches all internal nodes which are not ancestral sequences -> should get 0
- `$sql_5` fetches all leaves which are ancestral sequences -> should get 0
Made a copy of `ensembl_compara_plants_51_104` –` ivana_copy_whole_compara_plants_51_104` on `mysql-ens-compara-prod-1` – and added 1 internal node which is not an ancestral sequence and 1 leaf which is an ancestral sequence. The datachecks failed.
```
INSERT INTO dnafrag VALUES (1, 10, 'TestLeaf', 4, 'ancestralsegment', 'NUC', 1, 5);
INSERT INTO dnafrag VALUES (2, 11, 'TestInternal', 5, 'reftig', 'NUC', 1, 10); …
```

Check the position of ancestral sequences in the genomic align trees

---

lib/Bio/EnsEMBL/DataCheck/Checks/RepeatFeatures.pm

Following discussion with James, adding repeatdetector as alternative to repeatmask in the analysis/feature check.
Tested.

Adding repeatdetector as alternative to repeatmask

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCompara.pm

When the registry includes the method `Bio::EnsEMBL::Registry->load_registry_from_url()`, several aliases are loaded by default (including `multi`, it seems). If only specific cores are loaded using `Bio::EnsEMBL::DBSQL::DBAdaptor->new()`, this alias is not added, making the DC fail. This is because `get_DBAdaptor()`, called from `get_dba()`, throws an error when the species/alias passed as an argument does not exist. Checking if it is there first fixes the issue, preserving the previous behaviour.
_Note:_ This has not been spotted earlier, neither is relevant for production e105, because it has been spotted doing a new "usage" of Compara's registry for a new Genebuild project (see [pan_genome registry](https://github.com/Ensembl/ensembl-compara/blob/feature/pan_genome_cmp/conf/pan_genome/ …

Bugfix for ControlledTablesCompara DC

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

In order to force the use of the most up-to-date centrally-managed databases (ensembl_metadata, ensembl-production, ncbi_taxonomy), don't allow those to be overridden by a server_uri parameter.

Use registry for metadata/production/taxonomy dbs.

---

lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesCommonName.pm
lib/Bio/EnsEMBL/DataCheck/index.json

The configuration requirements for this style of datacheck turn out to be too onerous - it is working across multiple core databases, and being able to locate all the relevant dbs is a pain. This requires further thought as to how it can best be integrated into our release processes, but for now, set it as advisory, so that it is not a blocker.

Set SpeciesCommonName datacheck to be advisory.

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCompara.pm

At a loss as to why this works and the other does not. For whatever reason, the previous way was incompatible with use in pipeline via `RunDataChecks.pm` and compara style registry, the taxonomy was undetectable. This has now been tested in both compara pipeline and manual datacheck commands, and appears to work. Needs to be merged ASAP to prevent blocking compara production pipelines.
[ENSCOMPARASW-4649](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-4649)

ControlledTablesCompara taxonomy compatibility with compara pipelines

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionNamesENA.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionNamesINSDC.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Added a check for Rapid Release display name.
Split the existing check on INSDC names into two, because only part of it is needed for exporting GFF3 formatted for ENA submission, and we want to be able to run just that bit. The INDSC name check requires all top-level sequences to have an INSDC name/synonym (rather than a set of named coord_systems), which matches the ENA submission use case.
Both of these datachecks are intended to be run within file dump pipelines, to check that the core databases contain all the information required for dumping (https://github.com/Ensembl/ensembl-production/pull/576).

File dump-related datacheck updates. 

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckIDRangeMLSS.pm
lib/Bio/EnsEMBL/DataCheck/index.json

We try to ensure IDs (i.e. `genomic_align_id`) are within the range `[mlss_id * 10 ^ 10 .. (mlss_id + 1) * 10 ^ 10]` for traceability. It was detected that some older IDs had not been set to adhere to this and although it's not a breaking issue it is good to flag any cases where this is not the case. This should only affect release DBs.  
This DC will check the following ID columns:
- `genomic_align.genomic_align_id`
- `genomic_align_block.genomic_align_block_id`
- `genomic_align_block.group_id`
- `genomic_align_tree.node_id`
- `constrained_element.constrained_element_id`
- `dnafrag.dnafrag_id`
- `conservation_score.genomic_align_block_id` 
**Related JIRA tickets:**
- ENSCOMPARASW-4632
Run against the (now fixed) `ensembl_compara_51_104` DB and passed. 
Before adding skip for pipeline DBs …

Check IDs are in correct range for associated MLSS ID

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneBounds.pm

tested on me1:premz_bombyx_mori_core_53_105_2
gene with stable_id "GeneID_4266952"
Just in case.
original gff
```
##sequence-region NC_002355.1 1 15643
NC_002355.1     RefSeq  gene    15095   15883   .       +       .       ID=gene-COX3;Dbxref=GeneID:4266952;Name=COX3;gbkey=Gene;gene=COX3;gene_biotype=protein_coding
NC_002355.1     RefSeq  CDS     15095   15883   .       +       0       ID=cds-NP_059480.1;Parent=gene-COX3;Dbxref=Genbank:NP_059480.1,GeneID:4266952;Name=NP_059480.1;gbkey=CDS;gene=COX3;product=cytochrome c oxidase subunit III;protein_id=NP_059480.1;transl_table=5
```
original gbff
```
CDS             1..262
/gene="COX3"
/locus_tag="KEF65_p01"
/coded_by="join(NC_002355.1:15095..15643,NC_002355.1:1..240)"
/transl_table=5
/db_xref="GeneID:4266952"
```

GeneBounds: fixing out-of-bound feature reports for circular seq_regions

---

lib/Bio/EnsEMBL/DataCheck/Checks/PepstatsAttributes.pm

Change the min_proportion to undef, because we need the number of
translations to be the number of attribs of each type. The value 1
basically meant that any number of attribs would work, as long as it
wasn't more than the number of translations.

Fix: should fail if not all translations have attribs

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckNonMinimisedGATs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckNonMinimisedGenAlnTrees.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Genomic align trees should always be binary (with the exception of EPO extended which may have 3 sequences).
We can check each parent node has an appropriate number of children and report the root id of any tree with issues. 
For full details see related ticket: [ENSCOMPARASW-4083](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-4083)
Tested on a database with mocked errors.

Check for non-minimised genomic align trees

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm

With very large numbers of genes, the datacheck loses connection to the database; an explicit disconnect solves this.
However, further optimisations may be required to account for the millions of genes that may be in otherfeatures databases, in order to reduce the memory footprint.

Add disconnect_if_idle to GeneBiotypes datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm

:bangbang: | This needs to be merged to handover compara vertebrates
:---: | :---
This compara DC checks for redundancy in homology relationships - duplicate relationships for a pair of `gene_members`.
But it does not take into account the possibility that a homology relationship can be identical and inferred from two different trees.
This flexibility has been checked on the staging sites and in the compara API, and causes no issues.
* Non default clustersets with overlapping mlsss in
in the strains/breeds and default can cause `gene_members`
to have duplicated relationships in different trees
* These "redundant" or duplicate relationships are actually
a sign of consistency between trees
* Whilst overlapping mlsss should be avoided in the future,
the data is not at fault, not technically …

Allow for differing clustersets/additional trees in homology relationships

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

Fix for EP-6693 where some pipelines receive species names postfixed with `_old` introduced by Datachecks when comparing previous databases releases.

Remove '_old' species DBAdaptor after running DbCheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/ChromosomesAnnotated.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MitochondriaAnnotated.pm
lib/Bio/EnsEMBL/DataCheck/index.json

We expect MT seq_regions to have a 'sequence_location' attrib, with a value of 'mitochondrial_chromosome'. This was only being checked if the coord_system name was 'chromosome' - but most new core dbs do not use that name, they have 'primary_assembly' instead.
This update splits out the MT stuff to a new datacheck, so that it does not depend on the coord_system name.

Check for mitochondrial attribute

---

lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionNamesINSDCAdvisory.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionNamesINSDCCritical.pm
lib/Bio/EnsEMBL/DataCheck/index.json

For new species, and most old ones, we have INSDC accessions for all of our sequences - this is really useful for users. Due to exceptional cases on the main Ensembl site, however, we don't enforce INSDC accessions, and the relevant datacheck was advisory.
For Rapid Release, however, this data should always be available, and we are introducing processes which depend on this (ENA-format GFF3 dumps, and the new metadata schema).
This PR makes the datacheck critical for RR, remaining advisory for the main site.

Enforce INSDC accessions as seq_region names or synonyms.

---

lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesCommonName.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Checking common names across a range of databases is awkward to do at handover, but things break if there are discrepancies, so we certainly want it as a critical datacheck.
The datacheck logically fits in the existing 'core_sync' group, which is convenient because we already run that as a post-handover pipeline, so don't need any additional process or config to incorporate the check.

Add common name check to core_sync group.

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
t/DbCheck_noncore.t
t/test-genome-DBs/multi/compara/meta.txt

The compara datachecks that needed to load core dbs, in order to check data consistency, were not working if both a registry and server_uri were provided. (If only one was provided, then assuming that the core dbs were on the given server, datachecks were fine.)
When registry and server_uri are given, the code looks in the metadata db, to try and work out the name of the requisite core db. This requires a division name (because three species are in two divisions, and we need to only return one of them at a time), but division metadata is formatted differently in compara dbs, compared to all the species-specific dbs.
Once we account for that formatting, everything works as expected.

Fix compara datacheck retrieval of core dbs.

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankEnums.pm
lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckDuplicatedTaxaNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSequenceTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesSetTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CigarCheck.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DatabaseCollation.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm
lib/Bio/EnsEMBL/DataCheck/Checks/WhitespaceCritical.pm
lib/Bio/EnsEMBL/DataCheck/index.json

For the compara blastocyst, the pipeine automatically datachecks the integrity of the data within the pipeline before copying to the per-species RR compara databases. This is a necessary precaution. However, certain schema checks are not necessary for the pipeline, because the pipeline database differs from the compara schema in engine and therefore use of key restraints. So here we have a dc_group specific to the pipeline that checks the same data as in the final RR compara dbs, but without any schema checks, since these are expected to differ, and will be run on the individual databases once copy has completed.
[ENSCOMPARASW-4960](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-4960)

New compara_blastocyst group for RR pipeline database checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankEnums.pm
lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckDuplicatedTaxaNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSequenceTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesSetTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CigarCheck.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DatabaseCollation.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm
lib/Bio/EnsEMBL/DataCheck/Checks/WhitespaceCritical.pm
lib/Bio/EnsEMBL/DataCheck/index.json

For the compara blastocyst, the pipeine automatically datachecks the integrity of the data within the pipeline before copying to the per-species RR compara databases. This is a necessary precaution. However, certain schema checks are not necessary for the pipeline, because the pipeline database differs from the compara schema in engine and therefore use of key restraints. So here we have a dc_group specific to the pipeline that checks the same data as in the final RR compara dbs, but without any schema checks, since these are expected to differ, and will be run on the individual databases once copy has completed.
[ENSCOMPARASW-4960](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-4960)

New compara_blastocyst group for RR pipeline_db checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareSchema.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MySQLStorageEngine.pm

There were failing schema related DCs for the compara RR databases. Whilst fixing this on compara side it was noticed that the DCs themselves needed slight tweaks too.
* `CompareSchema` DC was missing a particular syntax for `UNIQUE KEY` and `CONSTRAINTS` so this line has been added.
* `MySQLStorageEngine` was hardcoded to MyISAM engine check, which is fine for every database except the compara RR databases, which require InnoDB engine, so a ternary has been chucked in to fit.
[ENSCOMPARASW-4959](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-4959)
https://github.com/Ensembl/ensembl-compara/pull/363 <- for interest/further understanding
- Tested on RR db on `InnoDB` schema
- Tested on e104 and e105 main release compara

Fix Schema DCs to fit edgecases

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm

Description
Genebuild is using new pipelines,  apart from the standard one, for the annotations so we are adding new meta keys in genebuild.method to consider them. A discussion with Web and the other teams will be done to modify the existing ones.
Description

added new metakeys for genebuild

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

Example: Xenopus laevis (J_2021) - GCA_017654675.1

Allow for _ to be part of the display name format.

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

We'd like to use "," to separate common name from the strain in the species display name

Update DisplayNameFormat.pm -- use "," (release/105)

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

Adding support for "." and "#" to the display_name pattern for the DisplayNameFormat DC

 DisplayNameFormat support for "." and "#"  main

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

Adding support for "." and "#" to the display_name pattern for the DisplayNameFormat DC

DisplayNameFormat support for "." and "#"  (105)

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

Adding support for ",", "_", "." and "#" to the display_name pattern for the DisplayNameFormat DC.
(As in main)

DisplayNameFormat support for ",.#_" (106)

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

Adding support for "." and "#" to the display_name pattern for the DisplayNameFormat DC

DisplayNameFormat support for "." and "#"  (107)

---

lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm

Updated regex for method in VersionedGenes.pm in order to include the new genebuild pipelines (braker, anno, standard).
Marc, could you please double check that this will not affect any Production code?

updated method to add new genebuild metakeys

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareHGNCMultipleGenes.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Refactor `HGNCMultipleGenes` into `CompareHGNCMultipleGenes`.
The new DC will fail only if the increase in HGNC symbols assigned to multiple genes compared to the previous release is above 5%.

EP-7110: Refactor HGNCMultipleGenes to allow comparison with threshold

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareSchema.pm

During within-compara datachecks and following a schema change to distinguish `UNIQUE` columns with `BINARY` for case sensitivity it was flagged in `CompareSchema` that a different way of writing the schema is returned to the one provided in `table.sql` - which is again different to the one returned by `Travis` - so this is the easiest fix to ensure consistency. The two different ways of writing it are otherwise equivalent.
This has been tested on the current e107 Metazoa compara release database with the current compara `table.sql` schema fllowing initial failure (see below), and this fixes the issue.
```
--
```

Alternative compatibility for BINARY column schema

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm

When running the data checks after the xref pipeline, the following error was appearing, though not every time:
"The group of semaphored jobs is incomplete ! Some fan jobs (coming from dataflow_rule_id(s) Bio::EnsEMBL::Hive::DataflowRule=HASH(0x6a0ac10)) are missing a job on their funnel."
This happens due to setting the dataflow output id for branch #1 (funnel) before entering the loop for creating jobs (fan) and setting the dataflow output id for other branches (#3 and #4).
This fix doesn't affect the flow of the code or the jobs so it shouldn't have negative impacts.
Tests were run and they are succeeding.

Fix race condition for fan-funnel jobs

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

DC was failing for display name:
Leopardus geoffroyi (Geoffroy's cat) - GCA_018350155.1
Added apostrophe to regex
Have requested Anne review to make sure this won't cause problems for web

Allow for apostrophe's in display name, e.g. "Geoffroy's cat"

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankEnums.pm
lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckCAFETable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckComparaStableIDs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckEmptyLeavesTrees.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckFlatProteinTrees.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGeneGainLossData.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGeneTreeRootMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckJSONObjects.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckOrthologyQCThresholds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSequenceTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesTreeNodeAttr.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesTrees.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CigarCheck.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HighConfidence.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagThresholdDs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MemberProductionCounts.pm
lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UniqueKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/index.json

In order to improve compara processing efficiency and quality control of gene tree and homology data we have decided to integrate datachecks into the gene tree pipelines. Here I propose a new group: `compara_gene_tree_pipelines`, which has been tested on gene tree data as DCs that are expected to pass.
Compara use eHive pipeline databases to store our data before we copy the necessary data into a release database. This datacheck group is a subset of the `compara_gene_trees` group with datachecks removed that are not applicable to gene tree pipeline databases.
This DC group has been tested on a gene tree pipeline.

New compara gene tree specific pipeline group

---

lib/Bio/EnsEMBL/DataCheck/Checks/StrainType.pm
lib/Bio/EnsEMBL/DataCheck/index.json

This is my first DC from scratch so I apologise for any mistakes, but the test will be on Genebuild when we handover databases for RR34, if any issues pop up we will fix them immediately.
**Description**
We found that the value for strain.type meta key had been set incorrectly as "reference" for a db on RR, this DC should check that the value for strain.type can only be from the approved list (we can update this list as needed).

New DC for checking that value for strain.type meta key is from approved list

---

lib/Bio/EnsEMBL/DataCheck/Checks/DataFilesExist.pm

With data_file initial directory updates, the DC need updating to include division name in path.

Added division path to check data_files availability.

---

lib/Bio/EnsEMBL/DataCheck/Checks/VariationAncestralAllele.pm
lib/Bio/EnsEMBL/DataCheck/index.json

This datacheck is intented to make sure that, for human DBs, that the ancestral allele pipeline has ran - the pipeline populates the ancestral allele information for COSMIC and ClinVar variant sources. So the check makes sure these columns have data.

Datacheck - VariationAncestralAllele

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckComparaStableIDs.pm

For e105 there was some difficulty with gene tree `stable_id`s and `stable_id_history` mapping. This has been manually repaired, but it was flagged that there was some old legacy-created and painful edge-case nomenclature producing ugly `stable_ids` which did not follow the idea prefixes for gene trees. This check only checks the `"default"` `tree` tree-type trees that are expected to have this nomenclature. The `supertrees` are generally `PTHR` and are excepted in this case, and non-`default` trees are not expected to contain the prefix either, for example cultivars and strains trees follow a different nomenclature for gene tree `stable_id`.
Below is the expected output following correction of the data
```
CheckComparaStableIDs .. 
ok 1 - There are no NULL stable_ids in family
ok 2 - …
```

Prefix check for stable_ids in compara gene trees

---

lib/Bio/EnsEMBL/DataCheck/Checks/VariationClasses.pm

[ENSVAR-5000](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5000)
This datacheck is intended to make sure VariationClasses check is done based on the source of the variants.
The idea is if EVA is present in the source table then import was done using EVA so only EVA checks, if not present dbSNP check is done.

Changes to support EVA datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/RepeatFeatures.pm

Repeat analyses are not run on projection builds, so necessary to skip this test for those with genebuild.method=>'projection_build'

add skip repeat features for projection builds, e.g. human haplotypes

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm

To allow for human projections to pass DCs we need to allow a small number of genes to have transcripts that have different biotypes

For projection builds: Allow up to 100 gene with without a transcript that has a matching biotype

---

lib/Bio/EnsEMBL/DataCheck/Checks/CanonicalTranscripts.pm

skip canonical transcript checks for projection builds

fixed canonical transcripts for human

---

t/test-genome-DBs/collection/core/analysis_description.txt
t/test-genome-DBs/drosophila_melanogaster/core/analysis_description.txt

This PR updates retired Pfam URLs to the new site (InterPro).
Other affected repos listed in the JIRA ticket.
Webteam JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6701
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680

Update Pfam URLs

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckComparaStableIDs.pm

There was a typo in the plants stable ID prefix in the CheckComparaStableIDs check.

Fixed typo in stanble ID prefix in CheckComparaStableIDs.

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignments.pm

In Ensembl Protists Compara 109, there are 121 `TRANSLATED_BLAT_NET` MLSSes with genomic alignment data, but this method type is not in the `@method_links` array of known genomic alignment methods in the `CheckGenomicAlignments` datacheck, so the DC fails even though all the genomic alignment rows are associated with a known alignment method. This PR adds `TRANSLATED_BLAT_NET` to the array of known genomic alignment methods, allowing the datacheck to support alignments of this type.

Add tBLAT to known methods in CheckGenomicAlignments

---

lib/Bio/EnsEMBL/DataCheck/Checks/MitochondriaAnnotated.pm

Check if the mitochondria has the karyotype_rank attribute when chromosomes are presents, i.e other regions have a karyotype_rank attribute.
Check if the mitochondria does not have the karyotype_rank attribute when no chromosomes are present
This is linked to ENSINT-1417

Check karyotype_rank attribute for MT

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareGOXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGOXrefs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedGeneNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProjectedSynonyms.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareSynonym.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DisplayXrefExists.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DisplayXrefFormat.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GOXrefEvidence.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneDescriptions.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HGNCNumeric.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HGNCTypes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/NCBIGeneLabels.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ObjectXrefNull.pm
lib/Bio/EnsEMBL/DataCheck/Checks/StableIdDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptDisplayXrefSuffix.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UniProtDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UnreviewedXrefs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefFormat.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefPrefixes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefTypes.pm
lib/Bio/EnsEMBL/DataCheck/index.json

This new group would be used by the Gene Symbol Transformer pipeline to assign gene names in RapidRelease

New DC group xref_gene_symbol_transformer to allow for gene name duplication

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGOCScoreStats.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckWGACoverageStats.pm

The Compara datachecks `CheckGOCScoreStats` and `CheckWGACoverageStats` flag drops in GOC score or WGA coverage stats (respectively) relative to a previous release. These may fail due to changes in the proportions of homologies of different types, drops in the number of GOC/WGA stats in one or more homology types, or the complete loss of GOC/WGA stats relative to a previous release that had such stats.
This PR adds an additional subtest to each datacheck, which specifically checks for the complete loss of GOC/WGA stats in a given release, so that such data loss is more clearly flagged.

Add subtest to check for missing GOC or WGA scores

---

lib/Bio/EnsEMBL/DataCheck/Checks/ProteinFunctionPredictions.pm

[ENSVAR-4445](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4445):
* Check if `protein_function_predictions` has one or more rows.
* Check if `protein_function_predictions` and `protein_function_predictions_attrib` have data based on data types from `meta` table (`cadd`, `sift`, `polyphen` and `dbnsfp`).
* For the data types that are not available in the `meta` table, check if `protein_function_predictions` doesn't contain data for those data types.
Most species only have SIFT data, so this should not raise issues if the other data types are missing.
You can test a single datacheck with the following command: `perl ensembl-datacheck/scripts/run_datachecks.pl $(v2 details script) -dbname nuno_homo_sapiens_variation_109_38_outdated_citations -name ProteinFunctionPredictions -dbtype …

Improve protein_function_predictions data checks (e110)

---

lib/Bio/EnsEMBL/DataCheck/Checks/AltAllele.pm
lib/Bio/EnsEMBL/DataCheck/Checks/AltAlleleGroup.pm

Following work to create new Y-PAR genes in the core database for Release 110 (project summary: https://www.ebi.ac.uk/seqdb/confluence/display/ENSCORE/Y+PAR+Genes): 1) a gene can now belong to one or more alt allele groups, and 2) there is a new 'IS_PAR' alt allele relationship to link between X- and Y-PAR genes. 
These changes have caused the data check expected counts for AltAllele and AltAlleleGroup to fail. This PR fixes the issue by removing the alt allele groups containing the new 'IS_PAR' alt allele relationships from the data check counts.

Fix alt allele data checks by ignoring new IS_PAR relationships

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckAlphafoldEntries.pm

We used to store a 'chain' tag with the Alphafold accession, like this: AF-P63151-F1.A It was decided to drop that part (.A), as it is not currently used and creates more work.

Remove the 'chain' part for Alphafold accessions

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckAlphafoldEntries.pm

Alphafold inserts features without regard for the species.
The datacheck would check the same thing for every species in the collection.
Put a PER_DB = 1 to make it run only once for collections.

Run Alphafold checks only once for multispecies DB

---

lib/Bio/EnsEMBL/DataCheck/Checks/DataFilesExist.pm

In order to reflect the new regulatory build approach, we decided to remove the following checks:
- alignment_has_bigwig();
- segmentation_file_has_bigbed();
- motif_feature_has_bigbed();
We're still keeping the check's code as a safety measure since the mentioned approach is still being developed.
We expect to remove them in the next release.

Remove data_files related discontinued checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareProteinFunctionPredictions.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ProteinFunctionPredictions.pm
lib/Bio/EnsEMBL/DataCheck/index.json

VCF-only species have no predictions for protein function (empty tables for `protein_function_predictions` and `protein_function_predictions_attrib`). This PR ensures tests associated with ProteinFunctionPredictions are skipped for those species.
Test with two variation species with different variation sources:
* VCF:
```
perl ensembl-datacheck/scripts/run_datachecks.pl \
$(v1 details script) \
--old_server_uri $(v1 details url) \
--server_uri $(v1 details url) \
--name ProteinFunctionPredictions,CompareProteinFunctionPredictions \
--dbname coturnix_japonica_variation_110_2
```
* Database:
```
perl ensembl-datacheck/scripts/run_datachecks.pl \
$(v1 details script) \
--old_server_uri $(v1 details url) \
--server_uri $(v1 details url) \
--name …
```

Skip ProteinFunctionPredictions tests for VCF-only species

---

lib/Bio/EnsEMBL/DataCheck/Checks/MartDatasetName.pm

A dedicated BioMart species list file (`biomart_species.json`) has been added to the Vertebrates Compara species config in [Compara PR #583](https://github.com/Ensembl/ensembl-compara/pull/583).
This PR effectively configures the `MartDatasetName` to take the Vertebrates BioMart species list from the new `biomart_species.json` file instead of the Vertebrates `allowed_species.json` file.
Having the Vertebrates BioMart `biomart_species.json` file alongside the Vertebrates Compara `allowed_species.json` file will allow the Vertebrates Compara species to differ from the Vertebrates BioMart species, while still maintaining an automatic consistency check.
None expected.

Get Vertebrates BioMart species from dedicated file

---

lib/Bio/EnsEMBL/DataCheck/Checks/MemberProductionCounts.pm

MemberProductionCounts data check assumed that all collections have homoeologues which is not true. This DC was flagged up during release 111 for rice. This DC is now updated to handle the collections that do not have homoeologues.

Updated the MemberProductionCounts DC

---

lib/Bio/EnsEMBL/DataCheck/Checks/TimelySemaphoreRelease.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Early semaphore release issues affected several pipelines in e111. Such issues have been reported before, in e109 Vertebrates FTP dumps, [e105 Mammals EPOwithExt](https://genomes-ebi.slack.com/archives/D0255PFSNKW/p1625849995012100), [e103 default ncRNAtrees](https://www.ebi.ac.uk/seqdb/confluence/display/EnsCom/Intentions+for+release+103), and in [e96 Plants](https://www.ebi.ac.uk/seqdb/confluence/display/EnsCom/2019-02-27).
But the impact of this issue in e111 — one pipeline completely rerun, a second pipeline with out-of-sync homology data — calls for measures to catch such issues as soon as possible.
The aim of this PR is to create a datacheck (**TimelySemaphoreRelease**) which queries the semaphore and job tables to check that every dependent semaphore job was started only after all …

Added datacheck for timely release of eHive semaphors

---

lib/Bio/EnsEMBL/DataCheck/Checks/MemberXrefAccessTime.pm
lib/Bio/EnsEMBL/DataCheck/index.json

In Ensembl 109 the access time of Member Xref data from the Metazoa Compara database was prohibitively slow, causing gene-tree displays to fail with an Ajax error ([ENSWEB-6789](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6789)).
It has been proposed to develop a datacheck ([ENSCOMPARASW-6449](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-6449)) to catch and fix this kind of issue at an earlier stage in the release cycle.
This PR adds a datacheck (`MemberXrefAccessTime`) which tests that access of Member Xref data via the Compara Perl API is not prohibitively slow.
This datacheck is added to the `compara_annot_highlight` group so that it can be run as soon as the `member_xref` and `external_db` tables of the relevant Compara database have been populated.
Note that in the …

Add datacheck MemberXrefAccessTime

---

lib/Bio/EnsEMBL/DataCheck/Checks/CactusMetadataConsistency.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Issues have arisen in recent releases with Cactus genomic alignment metadata consistency: in one case a retired `GenomeDB` was present in the HAL mapping which links a Compara database to its configured Cactus alignments, and in another case a species in the HAL mapping was not present in the corresponding species tree. Tickets have been created proposing to develop a datatcheck for each of these issues ([ENSCOMPARASW-5088](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-5088) and [ENSCOMPARASW-6834](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-6834), respectively).
The datacheck which would be added by this PR tests both cases.
This PR adds a Compara datacheck (`CactusMetadataConsistency`) which tests that for each Cactus MLSS in a Compara database:
- a HAL mapping is …

Add datacheck CactusMetadataConsistency

---

lib/Bio/EnsEMBL/DataCheck/Checks/MartDatasetName.pm

With the introduction of a BioMart species list for Metazoa in e112, datacheck code which previously applied only to the Vertebrates division needs to be revised to apply also to the Metazoa division.
**Related JIRA tickets:**
- [ENSINT-1549](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-1549)
In the `MartDatasetName` datacheck, the mart species filter is extended so that it also matches on the Metazoa division.
The updated regex was tested locally to ensure that it correctly matched the strings `EnsemblVertebrates` and `EnsemblMetazoa`.

Extend MartDatasetName mart filter to Metazoa

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledAnalysis.pm

When bringing back old core dbs these can contain deprecated analyses and removing those can be quite painful and introduces the potential of making mistakes. If having these in the core db is not dangerous for Production or Web, it may be easiest to remove the requirement of an analysis to be current.
_Note:_ there is no need to add any other conditions since `logic_name` is UNIQUE in `analysis_description`, so there is no chance that two configurations of the same analysis are returned.

Update query to fetch analysis information

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm

Now that the meta_values are NULLable, this check is run on the meta table and, inevitably, there are empty strings in the meta_values.
To allow beta handover on schema 110, I'm skipping this check on the meta table.
I tested on my beta testing db
`perl /hps/nobackup/flicek/ensembl/genebuild/leanne/beta/handover_rr59/ensembl-datacheck/scripts/run_datachecks.pl -host mysql-ens-genebuild-prod-1 -port 4527 -user ensro -dbname amphiduros_pacificus_gca949316495v1_core_110_1 -dbtype core -n BlankNulls`
and it passed.

Skip checking the meta table for blanks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CanonicalMemberCore.pm
lib/Bio/EnsEMBL/DataCheck/index.json

In response to various issues encountered with canonical member discrepancies, this PR adds a Compara `CanonicalMemberCore` datacheck, which verifies that the canonical member of each coding gene in a Compara database matches the canonical sequence of that gene in the corresponding core database.
This PR adds a `core_sync` datacheck (`CanonicalMemberCore`) which compares the set of gene-to-canonical-member (versioned or unversioned stable ID) pairs in each GenomeDB against the gene-to-canonical (versioned or unversioned stable ID) pairs in the corresponding core database, flagging any discrepancies.
- [ENSCOMPARASW-7202](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-7202)
The datacheck was run on all Ensembl Compara 112 databases. It failed on all divisions except Metazoa Compara, …

Add CanonicalMemberCore datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/CactusMetadataConsistency.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignGenomeDBs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignments.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckMSANames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesTrees.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareMSANames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagMultipleAlignment.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MultipleGenomicAlignBlockIds.pm

This PR adds support for `CACTUS_DB` alignments to relevant datachecks.
Unlike with `CACTUS_HAL`, a `CACTUS_DB` MLSS can have alignment data in the database.
All the updated datachecks passed on `mysql-ens-compara-prod-8:4618/ensembl_compara_metazoa_60_113`.

Add datacheck support for CACTUS_DB alignment data

---

lib/Bio/EnsEMBL/DataCheck/Checks/StrainGeneTreeSpeciesSets.pm
lib/Bio/EnsEMBL/DataCheck/index.json

This PR would add a `StrainGeneTreeSpeciesSets` datacheck, which would help ensure that strain-level gene-tree species sets are configured as expected.
The main practical consequence would be that the `strain_type` species-set tag would be required for strain-level collections (e.g. Murinae, Rice cultivars), allowing for code updates depending on this tag.
The datacheck also verifies that no genome is present in more than one strain-level gene-tree species set, an implicit assumption of Compara and Web code dealing with strain-level gene trees.
The datacheck was tested on Vertebrates and Plants Compara release 112 and 113 databases  in an Ensembl 113 environment.
Database `ensembl_compara_113` has valid strain-type tags for both Mouse strains and Pig breeds, and had this datacheck output: …

Add StrainGeneTreeSpeciesSets datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm

During Ensembl 105, the homology redundancy check in `CheckHomology` was changed to allow for redundant homologies between two gene members if those homologies were in a different gene tree (and consequently had a different `gene_tree_root_id`).
This change was understandable in the context of Ensembl 105 production. Since then, Compara pipelines have been updated to more effectively deal with redundant homology data, and so the stricter homology redundancy check has become more appropriate again.
This PR would revert to using the stricter homology redundancy check.

Revert to stricter homology redundancy check

---

lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm

This PR would allow a `CACTUS_DB` MLSS to be linked to a species set that includes component `GenomeDBs`.
It isn't expected that any `CACTUS_DB` data would be present on a genome component. In particular, this datacheck would continue to fail on a database with `CACTUS_DB` `genomic_align` entries linked to a `DnaFrag` on a  component `GenomeDB`.

Allow components in CACTUS_DB MLSSes

---

lib/Bio/EnsEMBL/DataCheck/Checks/SupertreeTopology.pm
lib/Bio/EnsEMBL/DataCheck/index.json

This PR would add a `SupertreeTopology` datacheck to check that the topology of each supertree is as expected.
Supertree topology issues have been detected in at least three instances ([ENSINT-1546](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-1546), [ENSCOMPARASW-5047](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-5047) and [ENSCOMPARASW-7628](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-7628)), and have likely occurred in other cases.
This datacheck was tested on relevant Ensembl Compara 113 databases, failing on `ensembl_compara_113` with the following output:
```
SupertreeTopology ..
ok 1 - Every node in supertree must have at least one child
not ok 2 - Root of supertree must have at least two children
not ok 3 - Internal nodes of supertree must have two children
ok 4 …
```

Add SupertreeTopology datacheck

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareGeneNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareProteinCodingGeneNames.pm
lib/Bio/EnsEMBL/DataCheck/index.json

During recent releases, we've been receiving user queries about missing gene names as well as things we have noticed while investigating issues. Due to this, we've decided to add a new DC that compares the number of genes that have names (have a set display xref) and the sources that these names are coming from between 2 releases. This DC is part of the advisory checks that run at the end of the xref pipeline run.
This check will fail if the number of gene names decrease by more than 33%. The threshold can be increased or decreased as needed later on, when we have more of an idea on how this check performs among many species.

New DCs for Xref

---

lib/Bio/EnsEMBL/DataCheck/Checks/StrainGeneTreeSpeciesSets.pm

With my apologies, this is another fix in the `StrainGeneTreeSpeciesSets` datacheck.
This PR would remove this datacheck from the `compara_gene_tree_pipelines` group.
This datacheck requires a registry, but the integrated gene-tree pipeline datachecks which use the `compara_gene_tree_pipelines` group are not currently configured to use a registry.

Drop StrainGeneTreeSpeciesSets from compara_gene_tree_pipelines

---

lib/Bio/EnsEMBL/DataCheck/index.json

With my apologies again, this is yet another fix of the `StrainGeneTreeSpeciesSets` datacheck.
[ensembl-datacheck PR 606](https://github.com/Ensembl/ensembl-datacheck/pull/606) removed `compara_gene_tree_pipelines` from the group list of the  `StrainGeneTreeSpeciesSets` datacheck.
This PR would remove the `StrainGeneTreeSpeciesSets` datacheck from the `compara_gene_tree_pipelines` group in the `index.json`.

Fix StrainGeneTreeSpeciesSets groups in index.json

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareProteinCodingGeneNames.pm

Added a check to not consider PROJECTION xrefs when comparing protein-coding gene names as the PROJECTIONS wouldn't have been added at this level yet.

Xref DC Fix

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignGenomeDBs.pm

This PR would skip a component `GenomeDB` in the specific case where it is in a component-specific MLSS which has a matching `genome_component` MLSS tag.
For example, this would allow for component-specific alignment MLSSes such as `16 wheat_component_A Cactus` and `16 wheat_component_B Cactus` to include their respective A- and B- component genomes, making it possible to have multiple distinct `CACTUS_DB` MLSSes on the same set of species.

Skip component GenomeDBs if in matching component-specific MLSS

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareProteinCodingGeneNames.pm

The threshold should reflect 90% (instead of 10%). In addition, added a minimum count to ensure this doesn't fail for less than 5 records.

Fix threshold and add minimum count

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm

Removed check for genebuild.version=genebuild.start_date

---

lib/Bio/EnsEMBL/DataCheck/Checks/StrainGeneTreeSpeciesSets.pm

This PR updates the `StrainGeneTreeSpeciesSets` datacheck to support the `prefer_for_genome` gene-tree MLSS tag.
The `prefer_for_genome` tag will be used to make it possible for a small number of genomes to be present in both the Barley pangenome and Wheat cultivars protein tree collections. It allows such genomes to be assigned to one or the other protein-tree collection in those circumstances where we are constrained to choose one collection.
It adds the following tests:
- a test to ensure that all gene-tree MLSSes associated with a strain-level species set have consistent `prefer_for_genome` tags;
- a test to confirm that genomes listed in a `prefer_for_genome` attribute are in the associated species set; and
- a test to check that gene-tree MLSSes associated with a non-strain …

Validate prefer_for_genome MLSS tags, update known strain types
