Ensembl/ensembl-datacheck

lib/Bio/EnsEMBL/DataCheck/Checks/AssemblyExceptions.pm
lib/Bio/EnsEMBL/DataCheck/Checks/AssemblyTablesAcrossSpecies.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneCounts.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneGC.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GenomeStatistics.pm
lib/Bio/EnsEMBL/DataCheck/Checks/PepstatsAttributes.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/EmailReport.pm
lib/Bio/EnsEMBL/DataCheck/Test/DataCheck.pm
lib/Bio/EnsEMBL/DataCheck/index.json

(And a little bit of documentation tidying.)

Four new datachecks, two modified ones

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckChar.pm
lib/Bio/EnsEMBL/DataCheck/Checks/PhenotypeDescription.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Added CheckChar to DC. Please carefully review, as this is my first Perl script in years!

New tests/check char

---

lib/Bio/EnsEMBL/DataCheck/Checks/AssemblyConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareSchema.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CoordSystemConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Checks/FeatureBounds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesNameUnique.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
lib/Bio/EnsEMBL/DataCheck/Manager.pm
lib/Bio/EnsEMBL/DataCheck/index.json
t/Checks.t
t/DbCheck.t

New datachecks:
- SpeciesNameUnique
- CoordSystemConsistent
- FeatureBounds
- MetaTable
- CompareSchema
Plus better handling of registries for multi-database comparisons

New datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/SequenceLevel.pm

It looks like the present test doesn't accept any contig with a name? I think it should pass if it gets one row too.

Test should pass for 0 or 1 rows

---

lib/Bio/EnsEMBL/DataCheck/Checks/DNAEmpty.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/RepeatFeatureCoords.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionNamesINSDC.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionRank.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionTopLevel.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm
lib/Bio/EnsEMBL/DataCheck/Test/DataCheck.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Also includes fixes to problems I noticed with collection dbs using up all the connections.

New datachecks, mostly related to seq_regions

---

lib/Bio/EnsEMBL/DataCheck/Checks/ExonRank.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Quite simple ExonRank DC ready

ExonRank DC

---

lib/Bio/EnsEMBL/DataCheck/Checks/FeaturePosition.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SampleRegulatoryFeatureExists.pm
lib/Bio/EnsEMBL/DataCheck/index.json

FeaturePosition HC2DC

---

lib/Bio/EnsEMBL/DataCheck/Checks/AltAllele.pm
lib/Bio/EnsEMBL/DataCheck/Checks/AltAlleleGroup.pm
lib/Bio/EnsEMBL/DataCheck/index.json

New data checks for AltAllele and AltAllele group members check.

New test/alt allele

---

lib/Bio/EnsEMBL/DataCheck/Checks/AssemblyConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CoordSystemConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Checks/FeatureBounds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyAssembly.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyOptional.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Plus some tidying up of core-like 'consistency' datachecks.

Additional meta_key datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CanonicalTranscripts.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneStableID.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneStrands.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ProteinCodingGenes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UnversionedGenes.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Checking strands, stable IDs, versions and canonical transcripts, replicating the functionality of HCs: CanonicalTranscriptCoding, StableID, Strand, ProteinCodingGene, VersionedExons, VersionedGenes, VersionedTranscripts, VersionedTranslations

New datachecks for genes

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneCounts.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GeneGC.pm

Account for assembly patches, PAR, and LRG regions.

Alter SQL queries that do counting

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareGOXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareSynonym.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareXref.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Principally intended for new and old versions of the same db, but not restricted to that.

Advisory datachecks for comparing xref totals between two databases

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareAllele.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareBiotypeGroup.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareConsequenceTypes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareSynonym.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareXref.pm
lib/Bio/EnsEMBL/DataCheck/Test/DataCheck.pm
lib/Bio/EnsEMBL/DataCheck/index.json
t/TestDataCheck.t

Two new variation datachecks, tidying up a few other "Compare" datachecks, and making the behaviour of one of the testing methods more intuitive/sensible.

"Compare previous" datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateReadNames.pm

The SQL query have been changed

Duplicated read_files query changed

---

lib/Bio/EnsEMBL/DataCheck/Checks/FuncgenAnalysisDescription.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SampleRegulatoryFeatureExists.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm
lib/Bio/EnsEMBL/DataCheck/Test/DataCheck.pm
scripts/create_datacheck.pl
scripts/create_index.pl
scripts/run_datachecks.pl
scripts/run_pipeline.pl
t/RunDataChecks.t

Fixing typos, small improvements to scripts and diagnostics.

Miscellaneous tweaks

---

lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptVariation.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Converstion of HealthCheck TranscriptVariation.java
ENSVAR-1621

Add check for TranscriptVariation

---

lib/Bio/EnsEMBL/DataCheck/Checks/Variation.pm
lib/Bio/EnsEMBL/DataCheck/Checks/VariationFeature.pm
lib/Bio/EnsEMBL/DataCheck/Checks/VariationFeatureAlleles.pm
lib/Bio/EnsEMBL/DataCheck/Checks/VariationFeaturePAR.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion and update of HealthCheck VariationFeature.java - see ENSVAR-1624
Conversion and update of HealthCheck VariationFeatureAlleles.java - see ENSVAR-1625

Datachecks on Variation and VariationFeature

---

lib/Bio/EnsEMBL/DataCheck/Checks/ComparePhenotypeFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareVariationSets.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareVariationSources.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareVariationSynonyms.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion of healtcheck to datachecks for:
ComparePreviousVersionPhenotypeFeatures.java
ComparePreviousVersionVariationSets.java
ComparePreviousVersionVariations.java
ComparePreviousVersionVariationSynonyms.java

Four variation compare previous datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareGenotypes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareReadCoverage.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareSource.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareStructuralVariationStudies.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion of healthcheck to datacheck for:
ComparePreviousVersionGenotypes.java
ComparePreviousVersionReadCoverage.java
ComparePreviousVersionSources.java
ComparePreviousVersionStructuralVariations.java

New variation compare previous datachecks

---

lib/Bio/EnsEMBL/DataCheck/Checks/StructuralVariationFeature.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion and update of HealthCheck StructuralVariation.java  ENSVAR-1620

Datacheck for StructuralVariationFeature

---

lib/Bio/EnsEMBL/DataCheck/Checks/MultipleSeqRegions.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MultipleVariationClasses.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion of HealthCheck CheckNumerous.java - ENSVAR-1628
Split into 2 data checks
1) MultipleSeqRegions.pm - Checks for multiple seq_region_id in seq_region_id column in *_features tables
2) MultipleVariationClasses.pm - Checks for multiple classes in Variation

Add datachecks for multiple values

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareSampleDisplays.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Conversion of HealthCheck ComparePreviousVersionSampleDisplay.java - ENSVAR-1970

Datacheck for comparing sample counts by display between databases

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSubmission.pm

Datachecks were using history and output parameters from a config file correctly, but they were not being stored/reported - this change ensures that they appear in the database logs and email summaries.

Detect history and output parameters from a config file

---

lib/Bio/EnsEMBL/DataCheck/Checks/ChromosomesAnnotated.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyAssembly.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DataCheckSummary.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm

Some minor changes to datacheck pipeline; a few tweaks based on feedback from running datachecks on metazoa; comprehensive testing on liftover meta_keys for assembly conversion.

Sundry updates and fixes

---

lib/Bio/EnsEMBL/DataCheck/Checks/PhenotypeMultipleSeqRegions.pm
lib/Bio/EnsEMBL/DataCheck/index.json
t/test-genome-DBs/homo_sapiens/variation/meta.txt
t/test-genome-DBs/homo_sapiens/variation/table.sql

Merge branch 'release/99' into master, to pick up test db changes, otherwise we'll get spurious test failures when we commit to master.

Merge release 99

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/RunDataChecks.pm
t/RunDataChecks.t

Fixes bug in previous bug fix...

Won't always have a DBA, so make the parsing of its parameters conditional

---

scripts/create_datacheck_tickets.pl
scripts/create_jira_tickets.pl

See [ENSCOMPARASW-2696](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-2696).

Added script to create JIRA tickets from failed datachecks

---

lib/Bio/EnsEMBL/DataCheck/index.json

I incorrectly resolved a merge conflict with my last commit, this fixes things properly...

Fixing index

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareStableIdsMapping.pm
lib/Bio/EnsEMBL/DataCheck/index.json

I know I'm not supposed to write inline comments but I think it would make the description of the test very long
As github says it, it's my first ever PR to this repository, so please if you prefer some parts to be written differently, now is the time

Test to check stable id mapping between two releases

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ExonBounds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm
lib/Bio/EnsEMBL/DataCheck/Manager.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm

Clearing up a few bugs, see individual commit messages for full details.

Miscellaneous small bugfixes

---

lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm

Found while DC-ing the new Plants database.

bugfix: the "ancestral_sequences" genome_db is not expected to be in any species set

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckConservationScore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckConservationScorePerBlock.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignGenomeDBs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignMTs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckLastZCoverage.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckMultipleAlignCoverage.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckOrthologyQCThresholds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckPairAlignerUniqueMethod.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSyntenySanity.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckTableSizes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareMSANames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HighConfidence.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MemberProductionCounts.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MultipleGenomicAlignBlockIds.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

Changes required to make the DCs pass on the GRCh37 and Pan databases

Updates to support GRCh37 and Pan

---

lib/Bio/EnsEMBL/DataCheck/Checks/DescriptionNewlines.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GOXrefEvidence.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SharedDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/StableIdDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptDisplayXrefSuffix.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UniProtDisplayXref.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UnreviewedXrefs.pm
lib/Bio/EnsEMBL/DataCheck/Checks/XrefFormat.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Converted DescriptionNewline Health check to datacheck

Ensprod 4980

---

lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CoreTables.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DataFilesExist.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ExonBounds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/FeaturePosition.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MartDatasetName.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaCoord.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesTaxonomy.pm
lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptBounds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ValidTranslations.pm
lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
scripts/parse_results.pl

Lots of fixes and tweaks for various datachecks. There's a commit per datacheck, so you can look at the commit messages to understand what's being fixed in each case...

Assorted fixes

---

lib/Bio/EnsEMBL/DataCheck/Checks/ChromosomesAnnotated.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MTCodonTable.pm
scripts/parse_results.pl

Plus a fix for the output parsing script.

chrMT datacheck updates

---

lib/Bio/EnsEMBL/DataCheck/Checks/Publication.pm

Datacheck is checking duplicated NULL values. This PR makes sure those values are not included when checking duplicates. 
Ticket: ENSVAR-3010

Publication duplicated values

---

lib/Bio/EnsEMBL/DataCheck/Checks/EmptyVariationTables.pm
lib/Bio/EnsEMBL/DataCheck/Checks/IndividualType.pm

IndividualType is failing for species that have individual records but no species specific tests -
see ENSVAR-3112
The dog species name has been updated. Update checks that use dog species name - see ENSVAR-3180

Updates to IndividualType and EmptyVariationTables

---

lib/Bio/EnsEMBL/DataCheck/Checks/DataFilesExist.pm

This avoids having to specify the data_file_path parameter in a config file, if it's not needed anyway; and also prevents unnecessary connections to related core dbs.

Skip data_file existence check if not relevant

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm

Update Test to accept Viruses

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/EmailNotify.pm

Adding the pipeline name in the mail subject will ease the sort mail box.

pipeline name added in emailnotify subject

---

lib/Bio/EnsEMBL/DataCheck/Checks/MultipleSeqRegions.pm

Skip for division based on approach in PhenotypeMultipleSeqRegions
This is also needed for release/100
Should a separate PR be made on release/100?

Skip check for EnsemblViruses

---

lib/Bio/EnsEMBL/DataCheck/Checks/Publication.pm

Don't check if 'doi' is duplicated.

Variation Publication

---

lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm

This updated matches the [PR#224](https://github.com/Ensembl/ensj-healthcheck/pull/224) submitted to `ensj-healthcheck`.

Plants species-tree is now populated

---

lib/Bio/EnsEMBL/DataCheck/Checks/RNASeqDNAAlignFeatureAnalyses.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Check that all DNA alignment features are linked to an RNA-seq DNA alignment feature analysis and all RNA-seq DNA alignment feature analyses are linked to a DNA alignment feature.

RNA-seq daf analyses and features checks.

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

If so, use the dba->species value.

Test if MetaContainer adaptor is undef when determining the species

---

scripts/parse_results.pl

fix for Module name changed from DatacheckTapTOJson to ConvertTaptoJson

fixed datacheck module ConvertTapToJson not found error

---

lib/Bio/EnsEMBL/DataCheck/Checks/ProteinFunctionPredictions.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Check for NULL values as found in earlier releases.
Will review schema for protein_function_predictions

Check for ProteinFunctionPredictions table

---

scripts/parse_results.pl

Fix 'Undefined subroutine &main::pod2usage' when running parse_results.pl --help

Add Pod::Usage module

---

lib/Bio/EnsEMBL/DataCheck/Checks/ExonRank.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GOXrefEvidence.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HGNCNumeric.pm
lib/Bio/EnsEMBL/DataCheck/Checks/HGNCTypes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ValidTranslations.pm

A few datachecks had queries that were very inefficient - a few tweaks vastly improve execution time.

Optimise datachecks for collection dbs

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckFamiliesMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckGeneTreeRootMLSS.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Another oversight, see PR #292 for the same

Missing MLSS checks from PR #292

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckOntologyTerm.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareOntologyTerm.pm
lib/Bio/EnsEMBL/DataCheck/Test/DataCheck.pm
lib/Bio/EnsEMBL/DataCheck/index.json
t/TestDataCheck.t

- CompareOntologyTerm to test each ontology namespace alone
- Add CheckOntologyTerm to test presence of critical accession IDs
Cherry Pick of #295

Update Ontology Tests & row_subtotals

---

lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagHomology.pm

Replicating #310 on release/103 branch.

Add check for ncrna tags based on the gene trees available

---

lib/Bio/EnsEMBL/DataCheck/Checks/DensityFeatures.pm

Fix problem where datacheck was expecting density features on small seq_regions which the core stats pipeline skips.

DensityFeatures update, add threshold for expectations

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm

Added a couple of URL validity tests

added several checks for URLs in metakeys

---

lib/Bio/EnsEMBL/DataCheck/Checks/MartDatasetName.pm

If release branch doesn't yet exist for biomart repo, use master. Changed from using the 'current' release in the metadata db to the one that matches the core db being tested - if that doesn't exist yet, fall back to the previous release (otherwise, databases are not tested against others that have already been handed over for the active release, only the last release's databases, so name clashes could be missed). Refactored the code to remove unnecessary functions and redundant comments, and simplified the way the test iterates over divisions.

Making MartDatasetName more robust

---

lib/Bio/EnsEMBL/DataCheck/Checks/AssemblySeqregion.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CompareMetaKeys.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ControlledTablesCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CoreTables.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DNAFragCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DatabaseSpeciesName.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DensityFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ExonBounds.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysMultiDB.pm
lib/Bio/EnsEMBL/DataCheck/Checks/GenomeDBCore.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MLSSTagHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaCoord.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConsistent.pm
lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm
lib/Bio/EnsEMBL/DataCheck/Checks/PlastidsAnnotated.pm
lib/Bio/EnsEMBL/DataCheck/Checks/RepeatFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionSynonyms.pm
lib/Bio/EnsEMBL/DataCheck/Checks/UniqueKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/WhitespaceAdvisory.pm
lib/Bio/EnsEMBL/DataCheck/Checks/WhitespaceCritical.pm
lib/Bio/EnsEMBL/DataCheck/Manager.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Merging release/103 into master

Merging release/103 into master

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm

Tested on metazoan species for release 104(51) on me1.

adding new "import_build" genebuild.method to use by metazoan cores for versioned Apollo based imports

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

Report bugfix from PR #344 on release 104 branch

Report bug fix from PR #344 on release 104

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm

Report back bug fix fro PR #344 onto release/103

Report bug fix from PR #344 on release 103

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm

This is a little awkward - and I have no idea why it worked when I was initially testing (it does not work now).
See #351 - recent related PR.

Bugfix incorrectly expressed regular expression

---

lib/Bio/EnsEMBL/DataCheck/Checks/Denormalized.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Moved Denormalized.pm in a new dedicated group

New DC group "long_running_dc" for Denormalized.pm

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyConditional.pm

Replicating #361 on release/104 branch.

Division-specific repeatmasking

---

lib/Bio/EnsEMBL/DataCheck/Checks/MetaKeyFormat.pm

Non-ASCII characters in the meta_value of start_date meta_keys cause compara to break (this field is loaded into genome_db tables in compara dbs).
Also, check if start_date is the same as version - it shouldn't be, that indicates that version is not being used for its intended purpose.

Check format of 'genebuild.start_date'

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareMetaKeys.pm

Fix ENSPROD-7007 ignoring changes in LRG regions

EP-7007: Fix failures due to LRG insertion contigs

---

lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptSupport.pm

Added DC for is_canonical transcript attrib.

New required transcript attrib for all canonical transcript

---

lib/Bio/EnsEMBL/DataCheck/Checks/BlankEnums.pm
lib/Bio/EnsEMBL/DataCheck/Checks/BlankNulls.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckDuplicatedTaxaNames.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomology.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckHomologyMLSS.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSequenceTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CheckSpeciesSetTable.pm
lib/Bio/EnsEMBL/DataCheck/Checks/CigarCheck.pm
lib/Bio/EnsEMBL/DataCheck/Checks/DatabaseCollation.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ForeignKeysCompara.pm
lib/Bio/EnsEMBL/DataCheck/Checks/NoDataOnGenomeComponents.pm
lib/Bio/EnsEMBL/DataCheck/Checks/WhitespaceCritical.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Reverts Ensembl/ensembl-datacheck#421
Prefer to wait for everyone's validation.

Revert "New compara_blastocyst group for RR pipeline database checks"

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

Same as #419 but for `main` branch

Allow additional special charachters in DisplayNameFormat regex

---

lib/Bio/EnsEMBL/DataCheck/Checks/DuplicateComparaMemberXref.pm
lib/Bio/EnsEMBL/DataCheck/index.json

For upcoming GeneTreeHighlighting pipeline run. 
Related to:
- https://github.com/Ensembl/ensembl-compara/pull/362
- https://github.com/Ensembl/ensembl-production/pull/620

Added DuplicateComparaMemberXref DC

---

lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptSupport.pm

Fixed cmp_ok error when '=' ==> '=='

---

lib/Bio/EnsEMBL/DataCheck/DbCheck.pm
t/DbCheck.t

Division name included in the subtest header

Division name included in subtest header

---

lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm

Updated regex for method in VersionedGenes.pm in order to include the new genebuild pipelines (braker, anno, standard).

updated method to add new genebuild metakeys

---

lib/Bio/EnsEMBL/DataCheck/Checks/SpeciesTaxonomy.pm

See #ENSPROD-7682 related ticket

Allowing subspecies for plants division

---

.travis.yml

Added 5.26 to PERL build 
Expected upgrade to PERL 5.26
Code testing works with 5.26
TBD

Added PERL 5.26 to the build

---

lib/Bio/EnsEMBL/DataCheck/Checks/AnalysisWebDataFormat.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionGenomicProbeFeaturesByArray.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionGenomicProbeFeaturesByArrayWithProbeSets.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionProbeFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionProbeFeaturesByArray.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionProbes.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionTranscriptProbeFeaturesByArray.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionTranscriptProbeFeaturesByArrayWithProbeSets.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ReadFilePathEncrypted.pm
lib/Bio/EnsEMBL/DataCheck/index.json

New DCs for the regulation team.
All have been tested locally.

New regulation checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/VersionedGenes.pm

modified condition for Anno metakey

changed anno condition

---

lib/Bio/EnsEMBL/DataCheck/Checks/APPRISAttribValuesExist.pm
lib/Bio/EnsEMBL/DataCheck/Checks/APPRISCompareSource.pm
lib/Bio/EnsEMBL/DataCheck/index.json

APPRIS load test loaded file content. 
Tested with 107 dataset for MusMusculus - All good to go !

APPRIS load post load test compare with file content.

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/StoreResultToES.pm
scripts/run_pipeline.pl

Hive module to store the dc results into Elastic search 
Tested with dc pipeline : http://guihive-rh7.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-hive-prod-1&port=4575&dbname=test_2_es_verts_107&passwd=xxxxx
details added into ticket : https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-7107

Store dc results to es

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm

For projection we can have polymorphic pseudogenes. 
the Dc will fail is the count is more than 5

skip human polymorphic pseudogene if count less than 5

---

lib/Bio/EnsEMBL/DataCheck/Checks/GeneBiotypes.pm

Fixed the logic for this DC and added on more exception for the pseudogene checks for "projection builds", i.e. humans

fixes for GeneBiotypes DC

---

lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionGenomicProbeFeaturesByArrayWithProbeSets.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionProbeFeatures.pm
lib/Bio/EnsEMBL/DataCheck/Checks/ComparePreviousVersionTranscriptProbeFeaturesByArrayWithProbeSets.pm

Just a few updates in some probe_mapping DCs to improve the output messages.

message updtaes in probe_mapping checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

Allowing appending "[tags]" to the display name
See related https://github.com/Ensembl/ensembl-datacheck/pull/508

Adding annotation source tag to the display name

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckComparaStableIDs.pm

Compara datacheck `CheckComparaStableIDs` has a gene-tree stable-ID prefix consistency check which compares the stable ID prefixes of a given division against a known prefix.
This fails if run on any gene-tree prefix not included in the hash used by the datacheck to store known stable ID prefixes (e.g. WormBase gene trees with stable ID prefix `WBGT`). To avoid having to update the datacheck for every gene-tree prefix that needs to be supported, this PR generalises the stable ID prefix subtest into two subtests: one to check that all relevant gene tree stable IDs follow the standard format (described in the [Compara documentation on gene tree stable IDs](https://www.ensembl.org/info/genome/compara/stable_ids.html) and implemented in the [Compara::StableId::Generator method …

Generalise CheckComparaStableIDs prefix subtest

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareVariationRows.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Tested human 109 - datacheck took 1 min to run.

Add variation dc to compare number of rows

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckGenomicAlignments.pm

After reviewing each differences, one file show important difference. Worth a check.

Added check on user running the script becaus

---

lib/Bio/EnsEMBL/DataCheck/Checks/CompareSpeciesAlias.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Added CompareSpeciesAlias Test

Created CompareSpeciesAlias

---

lib/Bio/EnsEMBL/DataCheck/Checks/VariationSetStructure.pm
lib/Bio/EnsEMBL/DataCheck/index.json

Change VariationSetStructure to be advisory

---

lib/Bio/EnsEMBL/DataCheck/Checks/CheckAlphafoldEntries.pm

Related
https://github.com/Ensembl/ensembl_nf/pull/1
https://github.com/Ensembl/ensembl-production/pull/790

Changed `alphafold_import` to `alphafold` to fix Biomart Tables length

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm
lib/Bio/EnsEMBL/DataCheck/Pipeline/StoreResultToES.pm

Default to ES with domain without PORT set.
Default to 'datacheck_results' index

Don't use port for indexes if not set. 

---

lib/Bio/EnsEMBL/DataCheck/Checks/SequenceChecksum.pm

translation attribute without protein_coding biotype

Update datacheck SequenceChecksum

---

lib/Bio/EnsEMBL/DataCheck/Checks/SequenceChecksum.pm

The tests for CDS checksums were failing because of the issue with not having a CDS unless you have a translation record. Code has been changed and verified as working on my local copy

CDS checksum test was failing

---

lib/Bio/EnsEMBL/DataCheck/Checks/SequenceChecksum.pm

Issue was in the checksum checks for human as lrgs were counted in the counts. If logic wants to switch back to not filtering LRGs or wants to be more complicated it can be. But at the moment it's just a simple boolean control.

Optionally skip LRGs checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/DisplayNameFormat.pm

We want this information to be part of the display name as well as the accession meta keys.

Add support for GCF in beta/rapid

---

lib/Bio/EnsEMBL/DataCheck/Checks/CanonicalTranscripts.pm

Canonical transcripts with missing `is_canonical` attributes are not currently being flagged because the existing canonical transcript consistency test is in a GENCODE-specific datacheck, which skips the test for any genome other than `homo_sapiens` or `mus_musculus`.
To circumvent this issue, this PR copies the canonical consistency test to the [CanonicalTranscripts datacheck](https://github.com/Ensembl/ensembl-datacheck/blob/730792d7d29b7175fec404033128865328a669e4/lib/Bio/EnsEMBL/DataCheck/Checks/CanonicalTranscripts.pm) so that it can be used to identify core databases in which some or all canonical transcripts lack an `is_canonical` attribute.
Here are the results of running the current `TranscriptSupport` datacheck on `gallus_gallus_core_112_7`:
```
TranscriptSupport .. 
1..0 # SKIP …
```

Copy canonical consistency test to CanonicalTranscripts

---

lib/Bio/EnsEMBL/DataCheck/Checks/SeqRegionBRC4.pm

Check that BRC names are not duplicated or missing.

Better BRC seq_region checks

---

lib/Bio/EnsEMBL/DataCheck/Checks/CanonicalMemberCore.pm

In response to various issues encountered with canonical member discrepancies, PR #578 added a `CanonicalMemberCore` datacheck which verifies that the canonical member of each coding gene in a Compara database matches the canonical sequence of that gene in the corresponding core database.
That left a gap in testing — noncoding genes — which this PR aims to fill.
This PR extends `CanonicalMemberCore` so that it checks all canonical members against the core database, whether coding or non-coding.
- [ENSCOMPARASW-7220](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-7220)
- [ENSCOMPARASW-7221](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-7221)
The updated datacheck was run on Human genes freshly loaded as part of a Compara member-loading Hive pipeline. See related Jira tickets …

Check all members in CanonicalMemberCore

---

lib/Bio/EnsEMBL/DataCheck/Checks/TranscriptDisplayXrefSuffix.pm

removed the single quote around the regex in TranscriptDisplayXrefSuffix datacheck

regex fix for TranscriptDisplayXrefSuffix

---

lib/Bio/EnsEMBL/DataCheck/Pipeline/DbDataChecks_conf.pm

Removed old hive version validation

remove hive version validation
